Importing basic Libraries

In [ ]:
import pandas as pd 
import numpy as np

Choose dataset file from Local Directory

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving titanicsurvival.csv to titanicsurvival (1).csv

Load dataset

In [ ]:
dataset = pd.read_csv('titanicsurvival.csv')
dataset

     Pclass     Sex   Age     Fare  Survived
0         3    male  22.0   7.2500         0
1         1  female  38.0  71.2833         1
2         3  female  26.0   7.9250         1
3         1  female  35.0  53.1000         1
4         3    male  35.0   8.0500         0
..      ...     ...   ...      ...       ...
886       2    male  27.0  13.0000         0
887       1  female  19.0  30.0000         1
888       3  female   NaN  23.4500         0
889       1    male  26.0  30.0000         1
890       3    male  32.0   7.7500         0

[891 rows x 5 columns]

Summarise  Dataset

In [ ]:
print(dataset.shape) # no of column and rows 
print(dataset.head(5)) # top 5 value set

(891, 5)
   Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

Mapping Text Data to Binary Value

In [ ]:
income_set = set(dataset['Sex'])
dataset['Sex'] = dataset['Sex'].map({'female':0, 'male':1}).astype(int)
print(dataset.head)

<bound method NDFrame.head of      Pclass  Sex   Age     Fare  Survived
0         3    1  22.0   7.2500         0
1         1    0  38.0  71.2833         1
2         3    0  26.0   7.9250         1
3         1    0  35.0  53.1000         1
4         3    1  35.0   8.0500         0
..      ...  ...   ...      ...       ...
886       2    1  27.0  13.0000         0
887       1    0  19.0  30.0000         1
888       3    0   NaN  23.4500         0
889       1    1  26.0  30.0000         1
890       3    1  32.0   7.7500         0

[891 rows x 5 columns]>

Segregate Dataset into X (input/IndependentVariable)&Y(Output/DependentVariable)

In [ ]:
X = dataset.drop('Survived',axis='columns')
X

     Pclass  Sex   Age     Fare
0         3    1  22.0   7.2500
1         1    0  38.0  71.2833
2         3    0  26.0   7.9250
3         1    0  35.0  53.1000
4         3    1  35.0   8.0500
..      ...  ...   ...      ...
886       2    1  27.0  13.0000
887       1    0  19.0  30.0000
888       3    0   NaN  23.4500
889       1    1  26.0  30.0000
890       3    1  32.0   7.7500

[891 rows x 4 columns]

In [ ]:
Y = dataset.Survived
Y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

Finding & Removing NA values from our Features X

In [ ]:
X.columns[X.isna().any()] # it is a method we have to learn accoerding to me

Index(['Age'], dtype='object')

In [ ]:
X.Age = X.Age.fillna(X.Age.mean())

Test again to check any na value

In [ ]:
X.columns[X.isna().any()]

Index([], dtype='object')

Splitting Dataset into Train & Test

In [ ]:
from sklearn.model_selection import train_test_split
X_train , X_test , Y_train , Y_test = train_test_split(X,Y, test_size = 0.25,random_state = 0 )

Training

In [ ]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train,Y_train)

GaussianNB()

Predicting wheather person Survivied or Not

In [ ]:
pclassNo = int(input("Enter person's Pclass number: "))
gender = int(input("Enter person's Gender 0-female 1-male(0 or 1): "))
age = int(input("Enter person's Age: "))
fare = int(input("Enter person's fare: "))
person = [[pclassNo,gender,age,fare]]
result = model.predict(person)
print(result)

if result == 1:
  print("person might be Survived")
else:
  print("person might not be survived")

Enter person's Pclass number: 2
Enter person's Gender 0-female 1-male(0 or 1): 0
Enter person's Age: 56
Enter person's fare: 45
[1]
person might be Survived

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  "X does not have valid feature names, but"

prediction for all test data

In [ ]:
Y_pred = model.predict(X_test)
#print(np.column_stack((Y_pred,Y_test)))

Accuracy of the model

In [ ]:
from sklearn.metrics import accuracy_score
print("Accuracy of the model: {0}%".format(accuracy_score(Y_test,Y_pred)*100))

Accuracy of the model: 77.57847533632287%